<a href="https://colab.research.google.com/github/amalvarezme/AnaliticaDatos/blob/master/leercovidCSV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install wget
import wget
import pandas as pd
#datos covid19 - mundo
url = "https://data.humdata.org/hxlproxy/api/data-preview.csv?url=https%3A%2F%2Fraw.githubusercontent.com%2FCSSEGISandData%2FCOVID-19%2Fmaster%2Fcsse_covid_19_data%2Fcsse_covid_19_time_series%2Ftime_series_covid19_confirmed_global.csv&filename=time_series_covid19_confirmed_global.csv"
#datos Colombia
#url = "https://www.datos.gov.co/api/views/gt2j-8ykr/rows.csv?accessType=DOWNLOAD"
wget.download(url, 'covid.csv')
Xd = pd.read_csv('covid.csv')
Xd

Requirement already satisfied: wget in /usr/local/lib/python3.6/dist-packages (3.2)

                Province/State         Country/Region  ...  4/18/20  4/19/20
0                          NaN            Afghanistan  ...      933      996
1                          NaN                Albania  ...      548      562
2                          NaN                Algeria  ...     2534     2629
3                          NaN                Andorra  ...      704      713
4                          NaN                 Angola  ...       24       24
..                         ...                    ...  ...      ...      ...
259  Saint Pierre and Miquelon                 France  ...        1        1
260                        NaN            South Sudan  ...        4        4
261                        NaN         Western Sahara  ...        6        6
262                        NaN  Sao Tome and Principe  ...        4        4
263                        NaN                  Yemen  ...        1        1

[264 rows x 93 columns]